

connect_debug_port u_ila_0/probe8 [get_nets [list {memcon/iram/mem_data_wdata_reg[15][0]} {memcon/iram/mem_data_wdata_reg[15][1]} {memcon/iram/mem_data_wdata_reg[15][2]} {memcon/iram/mem_data_wdata_reg[15][3]} {memcon/iram/mem_data_wdata_reg[15][4]} {memcon/iram/mem_data_wdata_reg[15][5]} {memcon/iram/mem_data_wdata_reg[15][6]} {memcon/iram/mem_data_wdata_reg[15][7]} {memcon/iram/mem_data_wdata_reg[15][8]} {memcon/iram/mem_data_wdata_reg[15][9]} {memcon/iram/mem_data_wdata_reg[15][10]} {memcon/iram/mem_data_wdata_reg[15][11]} {memcon/iram/mem_data_wdata_reg[15][12]} {memcon/iram/mem_data_wdata_reg[15][13]} {memcon/iram/mem_data_wdata_reg[15][14]} {memcon/iram/mem_data_wdata_reg[15][15]}]]


connect_debug_port u_ila_0/probe1 [get_nets [list {memcon/ram/activeRow[1]_6[0]} {memcon/ram/activeRow[1]_6[1]} {memcon/ram/activeRow[1]_6[2]} {memcon/ram/activeRow[1]_6[3]} {memcon/ram/activeRow[1]_6[4]} {memcon/ram/activeRow[1]_6[5]} {memcon/ram/activeRow[1]_6[6]} {memcon/ram/activeRow[1]_6[7]} {memcon/ram/activeRow[1]_6[8]} {memcon/ram/activeRow[1]_6[9]} {memcon/ram/activeRow[1]_6[10]} {memcon/ram/activeRow[1]_6[11]} {memcon/ram/activeRow[1]_6[12]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {memcon/ram/activeBankTimeout[3]__0[0]} {memcon/ram/activeBankTimeout[3]__0[1]} {memcon/ram/activeBankTimeout[3]__0[2]} {memcon/ram/activeBankTimeout[3]__0[3]} {memcon/ram/activeBankTimeout[3]__0[4]} {memcon/ram/activeBankTimeout[3]__0[5]} {memcon/ram/activeBankTimeout[3]__0[6]} {memcon/ram/activeBankTimeout[3]__0[7]} {memcon/ram/activeBankTimeout[3]__0[8]} {memcon/ram/activeBankTimeout[3]__0[9]} {memcon/ram/activeBankTimeout[3]__0[10]} {memcon/ram/activeBankTimeout[3]__0[11]} {memcon/ram/activeBankTimeout[3]__0[12]} {memcon/ram/activeBankTimeout[3]__0[13]} {memcon/ram/activeBankTimeout[3]__0[14]} {memcon/ram/activeBankTimeout[3]__0[15]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {memcon/ram/targetColumn[0]} {memcon/ram/targetColumn[1]} {memcon/ram/targetColumn[2]} {memcon/ram/targetColumn[3]} {memcon/ram/targetColumn[4]} {memcon/ram/targetColumn[5]} {memcon/ram/targetColumn[6]} {memcon/ram/targetColumn[7]} {memcon/ram/targetColumn[8]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {memcon/ram/activeRow[3]_4[0]} {memcon/ram/activeRow[3]_4[1]} {memcon/ram/activeRow[3]_4[2]} {memcon/ram/activeRow[3]_4[3]} {memcon/ram/activeRow[3]_4[4]} {memcon/ram/activeRow[3]_4[5]} {memcon/ram/activeRow[3]_4[6]} {memcon/ram/activeRow[3]_4[7]} {memcon/ram/activeRow[3]_4[8]} {memcon/ram/activeRow[3]_4[9]} {memcon/ram/activeRow[3]_4[10]} {memcon/ram/activeRow[3]_4[11]} {memcon/ram/activeRow[3]_4[12]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {memcon/ram/activeBankTimeout[1]__0[0]} {memcon/ram/activeBankTimeout[1]__0[1]} {memcon/ram/activeBankTimeout[1]__0[2]} {memcon/ram/activeBankTimeout[1]__0[3]} {memcon/ram/activeBankTimeout[1]__0[4]} {memcon/ram/activeBankTimeout[1]__0[5]} {memcon/ram/activeBankTimeout[1]__0[6]} {memcon/ram/activeBankTimeout[1]__0[7]} {memcon/ram/activeBankTimeout[1]__0[8]} {memcon/ram/activeBankTimeout[1]__0[9]} {memcon/ram/activeBankTimeout[1]__0[10]} {memcon/ram/activeBankTimeout[1]__0[11]} {memcon/ram/activeBankTimeout[1]__0[12]} {memcon/ram/activeBankTimeout[1]__0[13]} {memcon/ram/activeBankTimeout[1]__0[14]} {memcon/ram/activeBankTimeout[1]__0[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {memcon/ram/activeBankTimeout[0]__0[0]} {memcon/ram/activeBankTimeout[0]__0[1]} {memcon/ram/activeBankTimeout[0]__0[2]} {memcon/ram/activeBankTimeout[0]__0[3]} {memcon/ram/activeBankTimeout[0]__0[4]} {memcon/ram/activeBankTimeout[0]__0[5]} {memcon/ram/activeBankTimeout[0]__0[6]} {memcon/ram/activeBankTimeout[0]__0[7]} {memcon/ram/activeBankTimeout[0]__0[8]} {memcon/ram/activeBankTimeout[0]__0[9]} {memcon/ram/activeBankTimeout[0]__0[10]} {memcon/ram/activeBankTimeout[0]__0[11]} {memcon/ram/activeBankTimeout[0]__0[12]} {memcon/ram/activeBankTimeout[0]__0[13]} {memcon/ram/activeBankTimeout[0]__0[14]} {memcon/ram/activeBankTimeout[0]__0[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {memcon/ram/activeRow[0]_7[0]} {memcon/ram/activeRow[0]_7[1]} {memcon/ram/activeRow[0]_7[2]} {memcon/ram/activeRow[0]_7[3]} {memcon/ram/activeRow[0]_7[4]} {memcon/ram/activeRow[0]_7[5]} {memcon/ram/activeRow[0]_7[6]} {memcon/ram/activeRow[0]_7[7]} {memcon/ram/activeRow[0]_7[8]} {memcon/ram/activeRow[0]_7[9]} {memcon/ram/activeRow[0]_7[10]} {memcon/ram/activeRow[0]_7[11]} {memcon/ram/activeRow[0]_7[12]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {memcon/ram/activeBankTimeout[2]__0[0]} {memcon/ram/activeBankTimeout[2]__0[1]} {memcon/ram/activeBankTimeout[2]__0[2]} {memcon/ram/activeBankTimeout[2]__0[3]} {memcon/ram/activeBankTimeout[2]__0[4]} {memcon/ram/activeBankTimeout[2]__0[5]} {memcon/ram/activeBankTimeout[2]__0[6]} {memcon/ram/activeBankTimeout[2]__0[7]} {memcon/ram/activeBankTimeout[2]__0[8]} {memcon/ram/activeBankTimeout[2]__0[9]} {memcon/ram/activeBankTimeout[2]__0[10]} {memcon/ram/activeBankTimeout[2]__0[11]} {memcon/ram/activeBankTimeout[2]__0[12]} {memcon/ram/activeBankTimeout[2]__0[13]} {memcon/ram/activeBankTimeout[2]__0[14]} {memcon/ram/activeBankTimeout[2]__0[15]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {memcon/ram/targetBank[0]} {memcon/ram/targetBank[1]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {memcon/ram/targetRow[0]} {memcon/ram/targetRow[1]} {memcon/ram/targetRow[2]} {memcon/ram/targetRow[3]} {memcon/ram/targetRow[4]} {memcon/ram/targetRow[5]} {memcon/ram/targetRow[6]} {memcon/ram/targetRow[7]} {memcon/ram/targetRow[8]} {memcon/ram/targetRow[9]} {memcon/ram/targetRow[10]} {memcon/ram/targetRow[11]} {memcon/ram/targetRow[12]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {memcon/ram/activeRow[2]_5[0]} {memcon/ram/activeRow[2]_5[1]} {memcon/ram/activeRow[2]_5[2]} {memcon/ram/activeRow[2]_5[3]} {memcon/ram/activeRow[2]_5[4]} {memcon/ram/activeRow[2]_5[5]} {memcon/ram/activeRow[2]_5[6]} {memcon/ram/activeRow[2]_5[7]} {memcon/ram/activeRow[2]_5[8]} {memcon/ram/activeRow[2]_5[9]} {memcon/ram/activeRow[2]_5[10]} {memcon/ram/activeRow[2]_5[11]} {memcon/ram/activeRow[2]_5[12]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {memcon/ram/activeBank[0]_0}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {memcon/ram/activeBank[1]_1}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {memcon/ram/activeBank[2]_2}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {memcon/ram/activeBank[3]_3}]]
connect_debug_port u_ila_0/probe16 [get_nets [list memcon/ram/targetUL]]

