set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# Ports
set_property PACKAGE_PIN C8 [get_ports led_1_n]
set_property PACKAGE_PIN D8 [get_ports led_2_n]

# button 0
set_property PACKAGE_PIN H18 [get_ports rst_n_in]
set_property PACKAGE_PIN H17 [get_ports button_1_n]
set_property PACKAGE_PIN R2 [get_ports clk_50_in]

# set_property PACKAGE_PIN V2 [get_ports clk_out]
# set_property IOSTANDARD LVCMOS33 [get_ports clk_out]
# 
# set_property PACKAGE_PIN T3 [get_ports rst_n_out]
# set_property IOSTANDARD LVCMOS33 [get_ports rst_n_out]
# 
# set_property PACKAGE_PIN P3 [get_ports led_1_n_out]
# set_property IOSTANDARD LVCMOS33 [get_ports led_1_n_out]
# 
# set_property PACKAGE_PIN L4 [get_ports clk_out_true]
# set_property IOSTANDARD LVCMOS33 [get_ports clk_out_true]
# 
set_property PACKAGE_PIN P16 [get_ports s_clk]
set_property PACKAGE_PIN R16 [get_ports s_cke]

set_property PACKAGE_PIN N16 [get_ports {s_dqm[1]}]
set_property PACKAGE_PIN V16 [get_ports {s_dqm[0]}]

set_property PACKAGE_PIN U14 [get_ports s_cas_n]
set_property PACKAGE_PIN V14 [get_ports s_ras_n]
set_property PACKAGE_PIN U15 [get_ports s_we_n]
set_property PACKAGE_PIN V13 [get_ports s_cs_n]

set_property PACKAGE_PIN U12 [get_ports {s_bs[1]}]
set_property PACKAGE_PIN V12 [get_ports {s_bs[0]}]

set_property PACKAGE_PIN P15 [get_ports {s_addr[12]}]
set_property PACKAGE_PIN R15 [get_ports {s_addr[11]}]
set_property PACKAGE_PIN V11 [get_ports {s_addr[10]}]
set_property PACKAGE_PIN T15 [get_ports {s_addr[9]}]
set_property PACKAGE_PIN P14 [get_ports {s_addr[8]}]
set_property PACKAGE_PIN T14 [get_ports {s_addr[7]}]
set_property PACKAGE_PIN T13 [get_ports {s_addr[6]}]
set_property PACKAGE_PIN R13 [get_ports {s_addr[5]}]
set_property PACKAGE_PIN T12 [get_ports {s_addr[4]}]
set_property PACKAGE_PIN U9 [get_ports {s_addr[3]}]
set_property PACKAGE_PIN V9 [get_ports {s_addr[2]}]
set_property PACKAGE_PIN U10 [get_ports {s_addr[1]}]
set_property PACKAGE_PIN U11 [get_ports {s_addr[0]}]

set_property PACKAGE_PIN P18 [get_ports {s_dq[0]}]
set_property PACKAGE_PIN R18 [get_ports {s_dq[1]}]
set_property PACKAGE_PIN R17 [get_ports {s_dq[2]}]
set_property PACKAGE_PIN T18 [get_ports {s_dq[3]}]
set_property PACKAGE_PIN T17 [get_ports {s_dq[4]}]
set_property PACKAGE_PIN U17 [get_ports {s_dq[5]}]
set_property PACKAGE_PIN V17 [get_ports {s_dq[6]}]
set_property PACKAGE_PIN U16 [get_ports {s_dq[7]}]
set_property PACKAGE_PIN N17 [get_ports {s_dq[8]}]
set_property PACKAGE_PIN N18 [get_ports {s_dq[9]}]
set_property PACKAGE_PIN M16 [get_ports {s_dq[10]}]
set_property PACKAGE_PIN M17 [get_ports {s_dq[11]}]
set_property PACKAGE_PIN K17 [get_ports {s_dq[12]}]
set_property PACKAGE_PIN L18 [get_ports {s_dq[13]}]
set_property PACKAGE_PIN K18 [get_ports {s_dq[14]}]
set_property PACKAGE_PIN J18 [get_ports {s_dq[15]}]

set_property PACKAGE_PIN L5 [get_ports {gpio[0]}]
set_property PACKAGE_PIN L4 [get_ports {gpio[1]}]
set_property PACKAGE_PIN K3 [get_ports {gpio[2]}]
set_property PACKAGE_PIN K5 [get_ports {gpio[3]}]
set_property PACKAGE_PIN P1 [get_ports {gpio[4]}]
set_property PACKAGE_PIN R1 [get_ports {gpio[5]}]
set_property PACKAGE_PIN N1 [get_ports {gpio[6]}]
set_property PACKAGE_PIN N2 [get_ports {gpio[7]}]
set_property PACKAGE_PIN M2 [get_ports {gpio[8]}]
set_property PACKAGE_PIN M1 [get_ports {gpio[9]}]
set_property PACKAGE_PIN J5 [get_ports {gpio[10]}]
set_property PACKAGE_PIN J4 [get_ports {gpio[11]}]
set_property PACKAGE_PIN J6 [get_ports {gpio[12]}]
set_property PACKAGE_PIN K6 [get_ports {gpio[13]}]
set_property PACKAGE_PIN L2 [get_ports {gpio[14]}]
set_property PACKAGE_PIN L3 [get_ports {gpio[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n_in]
set_property IOSTANDARD LVCMOS33 [get_ports button_1_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50_in]

set_property IOSTANDARD LVCMOS33 [get_ports led_1_n]
set_property IOSTANDARD LVCMOS33 [get_ports led_2_n]
set_property IOSTANDARD LVCMOS33 [get_ports s_clk]
set_property IOSTANDARD LVCMOS33 [get_ports s_cke]
set_property IOSTANDARD LVCMOS33 [get_ports s_cas_n]
set_property IOSTANDARD LVCMOS33 [get_ports s_ras_n]
set_property IOSTANDARD LVCMOS33 [get_ports s_we_n]
set_property IOSTANDARD LVCMOS33 [get_ports s_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports {s_bs[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_dqm[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_addr[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_dq[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[*]}]

create_clock -period 20.000 [get_ports clk_50_in]
set_input_jitter [get_clocks -of_objects [get_ports clk_50_in]] 0.200

set_output_delay -max 1.5 -clock [get_clocks clk_50_in] [get_ports led_*]
set_output_delay -min -0.8 -clock [get_clocks clk_50_in] [get_ports led_*]
set_output_delay -max 1.5 -clock [get_clocks clk_50_in] [get_ports s_*]
set_output_delay -min -0.8 -clock [get_clocks clk_50_in] [get_ports s_*]
set_output_delay -max 1.5 -clock [get_clocks clk_50_in] [get_ports gpio[*]]
set_output_delay -min -0.8 -clock [get_clocks clk_50_in] [get_ports gpio[*]]
set_input_delay -max 5.0 -clock [get_clocks clk_50_in] [get_ports rst_n_in]
set_input_delay -min 2.5 -clock [get_clocks clk_50_in] [get_ports rst_n_in]
set_input_delay -max 5.0 -clock [get_clocks clk_50_in] [get_ports button_1_n]
set_input_delay -min 2.5 -clock [get_clocks clk_50_in] [get_ports button_1_n]
set_input_delay -max 5.0 -clock [get_clocks clk_50_in] [get_ports s_dq[*]]
set_input_delay -min 2.5 -clock [get_clocks clk_50_in] [get_ports s_dq[*]]
